default:
  just --list


build:
  go build -o tmp/main cmd/main.go

server:
  #!/usr/bin/env bash
  if command -v air > /dev/null; then
      air
      echo "Watching..."
  else
      read -p "Go's 'air' is not installed on your machine. Do you want to install it? [Y/n] " choice
      if [ "$$choice" != "n" ] && [ "$$choice" != "N" ]; then
          go install github.com/air-verse/air@latest
          air
          echo "Watching..."
      else
          echo "You chose not to install air. Exiting..."
          exit 1
      fi
  fi


[working-directory: 'frontend']
web:
  bun run dev
